### ISSUE TITLE
resource please

### ISSUE THREAD

**Issue by aplha98** [qamarelsafadi/ComposeMultiplatform#2]
Salam y moon, 
can you please share with us  your compose ios learning resource,
I am following PhilippLackner, android devs non of them talk about compose ios,
so please share with us that resource and any channel you recommended, and any kickstart

**Comment by qamarelsafadi** [comment]
Hello aplha98! 


There is no resource, especially for Compose IOS, 
once you start learning Compose you can use it for both Android and IOS. 

Unfortunately, until now there are no resources about Compose Multiplatform, especially for IOS because it's still experimental. 

So I recommend continuing learning Compose with Philip cause that means you are already can implement it in your IOS app as I did in this repo. 

**_Note_**: try to update compose dependency version, 
they update it and I read that they had improved IOS performance with it. 

Kindly close the issue if this answers your query.
